### ISSUE TITLE
The site http://worldtimeapi.org/ is not working

### ISSUE THREAD

**Issue by korshunns78** [nicolasbauw/world-time-api#2]
Hello, your site http://worldtimeapi.org has stopped working properly, I can access it 1 time out of 10, and yesterday I saw that the encrypted connection via https was gone. The problems started about a month ago, using a direct connection your site did not open, then I started using a proxy and got access to it without problems, but now I can not access it even using a proxy. Thank you for your attention, I hope you can fix this problem. Thank you for your project.
![Screenshot_24](https://github.com/user-attachments/assets/5e1a0538-8075-4a92-91a5-7a7458f5fe7f)
![Screenshot_25](https://github.com/user-attachments/assets/59706e51-b764-4989-91f1-2a49381e8363)

**Comment by nicolasbauw** [comment]
Hello,
I don't host this site, I can't help you with this issue !
It looks like they do not use my API (or a slightly modified version) : some fields are different.
More, my API uses HTTP, not HTTPS.
